package com.skycel.backend.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

@Entity
@Audited
@Table(name = "inventario_auditoria_detalle")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InventarioAuditoriaDetalle {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "iddetalle_inv")
    private Integer iddetalleInv;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idinventario", nullable = false)
    private InventarioAuditoria inventarioAuditoria;

    @Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idseccion", nullable = false)
    private Seccion seccion;

    @Column(name = "codpro", nullable = false, length = 25)
    private String codpro;

    @Column(name = "conteo", nullable = false, columnDefinition = "SMALLINT DEFAULT 1")
    private Short conteo;

    @Column(name = "stock_sistema", columnDefinition = "SMALLINT DEFAULT 0")
    private Short stockSistema;

    // "diferencia" is generated by the database entirely, so we set insertable/updatable to false
    @Column(name = "diferencia", insertable = false, updatable = false)
    private Integer diferencia;

    @Column(name = "estado", nullable = false, columnDefinition = "TINYINT")
    private Byte estado;
}
